### PR TITLE
adding reset_env function without using enforcer and passing softhsm par...

### PR DESCRIPTION
**Pull request by hodarh**
...ameters to reset_env functions if needed

### CODE REVIEW

**Comment by yschaeff** [comment]
#build bot build that built!

**Comment by yschaeff** [comment]
There seems to be an additional failure on the FreeBSD machine. Therefore not merging just yet.

**Comment by yschaeff** [comment]
yeah, can't see any code that might have caused this. Shall we give it another do #build bot?

**Comment by hodarh** [comment]
Yes, sure, can I do it now or I have to wait until the other ends?

**Comment by yschaeff** [comment]
It is running right now. Notice I used the magic word in my previous comment.

**Comment by yschaeff** [comment]
Well now an other test failed on another machine :-( Merging anyway.

**Pull request merged**
