### PR TITLE
Fixes to testsuite (OPENDNSSEC-645 OPENDNSSEC-652 OPENDNSSEC-657 OPENDNSSEC-665 OPENDNSSEC-685 OPENDNSSEC-686 OPENDNSSEC-687 OPENDNSSEC-688)

### PR DESCRIPTION
**Pull request by halderen**
#build

### CODE REVIEW

**Comment by halderen** [comment]
Why won't it #build 
#build 
already
#build

**Comment by halderen** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by halderen** [comment]
#build
pretty please, sugar on top.

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
Locally all tests pass (distro Slackware), hence I want to try to
#build 
again, and see the resu

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
Experimenting with even higher timeouts
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build after pushing

**Comment by halderen** [comment]
#build with a different strategy

**Comment by halderen** [comment]
#build with incorporation of OPENDNSSEC-685

**Comment by halderen** [comment]
#build to see whether test runs the same

**Comment by halderen** [comment]
#build makes test succeed

**Comment by halderen** [comment]
#build with unbuffer as alternative to stdbuf

**Comment by halderen** [comment]
#build again

**Comment by halderen** [comment]
#build again and again

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build need to push, waste of time this bloody github

**Comment by halderen** [comment]
#build with new fixes

**Comment by halderen** [comment]
#build with same source to compare two runs

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build experiment

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build now

**Comment by halderen** [comment]
#build with fix for ixfr test

**Comment by halderen** [comment]
#build again to see whether the run result stays stable

**Comment by halderen** [comment]
#build improvement for OPENDNSSEC-686

**Comment by halderen** [comment]
#build again

**Comment by halderen** [comment]
#build for mysql

**Comment by halderen** [comment]
#build again

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build and test again to see without changes still runs fine.

**Comment by halderen** [comment]
#build with more delays

**Comment by halderen** [comment]
#build with extra time for require_backup_and_do_backup test

**Comment by halderen** [comment]
#build with xml comparison improvements.

**Comment by halderen** [comment]
#build with xsltproc installed

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build debug core dump on freebsd10

**Comment by halderen** [comment]
#build with proper fix

**Comment by halderen** [comment]
#build again with higher timeout (in line with other tests)

**Comment by halderen** [comment]
We had a successful first #build now
#build again

**Comment by halderen** [comment]
#build with aligned test cases.

**Comment by halderen** [comment]
#build again to see whether it yields success a second time.

**Comment by halderen** [comment]
#build again to see whether it yields success a second time.

**Comment by halderen** [comment]
#build again to see whether it yields success a second time.

**Comment by halderen** [comment]
#build again to see whether is yields success a third time.

**Comment by halderen** [comment]
Final #build, when successful, ready to be merged.

Summary of changes:
GENERAL TEST ITEMS:
- do not retry test, they should /always/ succeed
  this was a big problem where many failures were in fact masked
- syslog wait is better then grep as it at least allows for a bit of time
- disabling buffering of tail follow using stdbuf
  - allow unbuffer as alternative to stdbuf
- Diff xml improvements
  - use xmllint and xsltproc to ensure the xml file is always in a
    canonical format.
- Disabled validns (only executed on redhat, not fully working anyway)
- importing policies, zonelist and directly stopping won't guarantee
  all signconfs are present.  Force writing signconf and wait a bit
  until it is there.
- build environment too slow for current settings and timing for
  signer to be ready on time.
- when setting up the test environment the signconf is not always generated
  by the enforcer (on time), do an explicit signconf (which may can fail
  when there are no zones) and a sleep will guarantee there is a signconf.
- verbosity increase of signer takes a while to propagate
OPENDNSSEC-685:
- zoneconf needs writing flag was not cleared after writing zoneconf
OPENDNSSEC-686:
- first update zones.xml, then flush enforce task.  This because enforce
  task will inform signer, which will need the updates zones.xml.
- mark further issue in source code
- sleep a bit of time in test to make sure file zones.xml timestamp will
  change
OPENDNSSEC-687:
- sleep to enforce that zone add/del are done before doing the next call.
OTHER:
- Drop unfinished, not working couchDB implementation.  This code
  causes "make dist" to break.
- make files executable which should be executable
- git ignore files which are generated during a test build
- add slackware to set of supported distros
OPENDNSSEC-645:
- confusement on zones and zonelist file (having same format, different
  purpose and formated differently)
OPENDNSSEC-665:
- Make the number of times the zone should get signed relative.
  Now the test checks a zone gets signed /again/ after a certain
  action.
- due to fix to OPENDNSSEC-684 the zone now gets signed
  immediately.  Since the script only checks for a specific
  number of times the zone gets signed, now (as would be
  needed) gets signed after an action, this breaks the test
  script
- also needs to increament a timeout for an update zone
OPENDNSSEC-657:
- due to fix to OPENDNSSEC-684 needs more time to load
  initial zones and spit out zoneconf.
OPENDNSSEC-652:
- longer sleep period after zone add for account for asyncronous workings
- longer sleeps after time leap necessary
- more time leaps necessary as zones are not processed at same time (see
  in file comment).
OPENDNSSEC-688:
- missing argument to ods_log_info caused segv on freebsd10 only strage
  enough.
LESSONS:
- All tests should always succeed, do not retry.
- Timeouts are bad, especially on individual commands.  Just timeout
  on the entire test suite. And;
- instead of only asserting on the success of a instruction, make
  an check that is based on the outcome of a (return of) a function
  that is always called (e.g. scheduler has run, or no more tasks
  queued) and then assert on whether your event was done or not.
- Asynchronous behaviour of the application, when not needed, is
  a bad thing.  This makes explicit sleep calls in the test
  necessary (esp when not doing the previous item) which is bad.
- Time leap should be able to leap to a specific time in steps.

**Comment by halderen** [comment]
Why won't it start to
#build

**Pull request merged**
