### PR TITLE
End time for DNSKEY TTL was not set properly. This could result

### PR DESCRIPTION
**Pull request by yschaeff**
in the enforcer rolling to quickly when the operator changes the
TTL for the DNSKEY to something smaller. Spotted in the database.

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
@halderen is it expected the machines are utterly broken?

**Comment by halderen** [comment]
I think it is important that bugs like this are supported by a unit test.  Also, make an issue in Jira, github is known to be really a bad tool for issue tracking.

**Comment by yschaeff** [comment]
Yes, we talked about that... The fact a unit test is not included in this PR does not mean I don't intend to. I _just_ quickly want to run it through Jenkins before making too much assumptions on correctness.

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
@halderen @hodarh, I made an issue for the testcase https://issues.opendnssec.org/browse/OPENDNSSEC-756. I propose to merge this in before creating that test. We have more pressing things to do.

**Pull request merged**
