### PR TITLE
ds-seen command: Show error messages when passing wrong arguments

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
ready to merge

**Comment by hodarh** [comment]
Yuri, thanks for your comments, I already removed all of those codes in my second commit, it was redundant, but still has memory leaks in some parts of code

**Comment by yschaeff** [comment]
Ah sorry, I completely missed the second commit!

**Pull request merged**
