### PR TITLE
OPENDNSSEC-641 test signer.adapters.output_tsig

### PR DESCRIPTION
**Pull request by halderen**

### CODE REVIEW

**Comment by halderen** [comment]
#build

**Comment by yschaeff** [comment]
I find it hard to make sense of this PR to review. What is new, what isn't, where does it come from? Could I maybe introduce you to the wonderfull world of rebasing?

**Comment by halderen** [comment]
I though you were the git master?  In the files changed you see only files in  testing/test-cases.d/signer.adapters.output_tsig/.. that have changed.  A quick diff with "git diff upstream/1.4/develop..halderen/OPENDNSSEC-641 testing/test-cases.d/signer.adapters.output_tsig" makes trivial output.  Otherwise its just being rebase-pedantic :-(

**Comment by yschaeff** [comment]
No, it is a misconception to think I know what I'm doing w.r.t. Git (or otherwise). Merely an enthousiast. Pedantic may be, I like the rebase concept. It keeps things more tidy.

**Comment by halderen** [comment]
#build

**Pull request merged**
