### PR TITLE
ds-seen test case

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by halderen** [comment]
#build with current trunk

**Comment by halderen** [comment]
On the test environment I re-ran the test including this addition.  I've verified and on the machines the test that runs immediately after enforcer.rollover.dsseen_good test now fails to set-up the test environment.  A number even indicating opendnssec is still running.  Hence there is still a problem with this one.

**Comment by hodarh** [comment]
#build

**Pull request merged**
