### PR TITLE
softhsmv2

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by bellgrim** [comment]
#build

Running build again, want to read the log files.

**Comment by bellgrim** [comment]
t looks like test case enforcer.database.migrate is failing.

Checking this: https://jenkins.opendnssec.org/view/pull-requests/job/pull-opendnssec-612-test/label=ubuntu14/7/console

It is failing because "LINE: 59 Both zones should use same KSK" is not true.

The current state is:
ods1;KSK;hidden;rumoured;rumoured;NA;1;1;76d553ff94f446d6b9fa60e4a20401c5
ods1;ZSK;NA;rumoured;NA;omnipresent;1;1;eb514ed41d3e0acdcabea63a5d236e73
ods2;KSK;hidden;unretentive;unretentive;NA;0;0;76d553ff94f446d6b9fa60e4a20401c5
ods2;ZSK;NA;rumoured;NA;omnipresent;1;1;eb514ed41d3e0acdcabea63a5d236e73
ods2;KSK;hidden;rumoured;rumoured;NA;1;1;bdbe7d1c5c028a61f1663ba3957f9891

The grep functions are then comparing these:
ods1;KSK;hidden;rumoured;rumoured;NA;1;1;76d553ff94f446d6b9fa60e4a20401c5
ods2;KSK;hidden;rumoured;rumoured;NA;1;1;bdbe7d1c5c028a61f1663ba3957f9891

Which are not the same key. ods2 has two KSK. The matching KSK to ods1 is an other state.

This error is not SoftHSM related.

The test is doing a rollover for ods2. So they should not be using the same KSK, right?

The grep for KSK2 and KSK3 will result in the same key as they both are looking for state 1;1 in a KSK for ods2.

**Pull request closed without merging**
