### PR TITLE
OPENDNSSEC-781: Change the module names of zone in enforcer.

### PR DESCRIPTION
**Pull request by hodarh**
Signer and enforcer both have zone obj and zone modules. Sometime even the names are the same like zone_create. By changing the name of modules in enforcer we avoid a clash when linking enforcer and signer into a single exe.

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
Please review and merge

**Comment by halderen** [comment]
Personally I would have named zone_list to zone_db_list in stead of zone_list_db.  But this is too minor to tribe over especially since this is the database layer.

**Pull request merged**
