### PR TITLE
Mm shortcut

### PR DESCRIPTION
**Pull request by yschaeff**

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
@halderen please merge this when you feel ready.

**Comment by halderen** [comment]
Can this be #build without a new commit?  Probably not, but attempt anyway.

**Comment by halderen** [comment]
Compilation error when compiling for mysql:
/usr/bin/cc -DHAVE_CONFIG_H -I. -I../../../enforcer/src -I../../common    -I../../../common -I../../common -I../../../enforcer/src/../../libhsm/src/lib -I./../../libhsm/src/lib -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/mysql  -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DPIC -fPIC -DUNDEF_HAVE_INITGROUPS -fno-strict-aliasing -g -O2 -pedantic -Wall -Wextra -pthread -MT db_backend_mysql.o -MD -MP -MF .deps/db_backend_mysql.Tpo -c -o db_backend_mysql.o `test -f 'db/db_backend_mysql.c' || echo '../../../enforcer/src/'`db/db_backend_mysql.c
../../../enforcer/src/db/db_backend_mysql.c: In function ‘__db_backend_mysql_prepare’:
../../../enforcer/src/db/db_backend_mysql.c:170: error: ‘mysql_statement_t’ undeclared (first use in this function)
../../../enforcer/src/db/db_backend_mysql.c:170: error: (Each undeclared identifier is reported only once
../../../enforcer/src/db/db_backend_mysql.c:170: error: for each function it appears in.)
../../../enforcer/src/db/db_backend_mysql.c:197: error: ‘mysql_bind_t’ undeclared (first use in this function)
../../../enforcer/src/db/db_backend_mysql.c: In function ‘db_backend_mysql_connect’:
../../../enforcer/src/db/db_backend_mysql.c:705: warning: passing argument 3 of ‘mysql_options’ from incompatible pointer type

**Comment by yschaeff** [comment]
#build

**Pull request merged**
