### PR TITLE
Cmdline crash3

### PR DESCRIPTION
**Pull request by yschaeff**

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
@halderen @hodarh sqlite test succes. Please review and merge. Contains fix so it builds on openssl 1.1.0.

**Comment by halderen** [comment]
Review done, one point, could you revert the change in
libhsm/src/lib/cryptoki_compat/pkcs11.h 
This file is actually not ours but part of the specification.  Not ours to change, and I would prefer not to give any hint that we change specifications or do something different..
Otherwise clear to merge.

**Comment by yschaeff** [comment]
@halderen I'd say it is an implementation of a specification. Therefore perfectly fine to touch. But sure, we can fix it in our own code as well. Feel free to merge my changes.

**Pull request merged**
