### PR TITLE
OPENDNSSEC-860: use getopt_long for processing arguments

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by halderen** [comment]
Can one of the admins verify this patch?

**Comment by halderen** [comment]
Can one of the admins verify this patch?

**Comment by hodarh** [comment]
resolved

**Pull request merged**
