### PR TITLE
adding timeleap commands to the test case

### PR DESCRIPTION
**Pull request by hodarh**
- ods_timeleap_seach_key function is jumping to the time that a specific key is available
- ods_timeleap_search_nokey function is jumping to the time that a specific key is gone

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by yschaeff** [comment]
I propose to add a failure condition to ods_timeleap_seach_key() and ods_timeleap_seach_nokey(). Right now, when this failes (e.g. key never appears) the test will never terminate. Have an extra argument "max number timeleaps" to those functions?

**Comment by halderen** [comment]
Does in currently fail to terminate ever?  If so, then yes such a thing can be added for now, however only as an optional parameter.
However this is not a permanent solution, rather than a timeout on every instruction, there should be a timeout on the entire test case only.  And this timeout should be set very large.  It should be there only to cover wild running tests.  There are a lot of problems with the test cases where the timeouts constantly need to be enlarged a bit to take account of a slightly longer time to finish execution.

**Comment by hodarh** [comment]
#build

**Pull request merged**
