### PR TITLE
Make janitor optional do aid debugging.

### PR DESCRIPTION
**Pull request by yschaeff**
TODO: handle cmdhandler joins
TODO: Make it a configuretime option.

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
Give me a B
Give me a U
Give me an I
Give me an L
Give me a D
Give me a #build

**Comment by yschaeff** [comment]
fluke? #build

**Comment by halderen** [comment]
Can one of the admins verify this patch?

**Comment by halderen** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
