### PR TITLE
OPENDNSSEC-694: Preserve the case of resource records.

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by halderen** [comment]
Ready for review/merge.

**Comment by halderen** [comment]
I also think this requires a test in the test suite.  Also note the issues refers not to the canonical domain names, but to the value of the PTR records!

**Comment by yschaeff** [comment]
@halderen OH! But that DOES make sense. It is one thing to fiddle with the owner name of a record (which should not matter as per the wire protocol) But another thing entirely to mess with the data of a RR. This changes my opinion entirely.

**Comment by yschaeff** [comment]
You are right berry, this patch only seems to canonicalize the dname, not the rdata the issue was about.

**Pull request merged**
