### PR TITLE
when revoking a key, set its dead time to fixed so later enforcer run…

### PR DESCRIPTION
**Pull request by yschaeff**
…s will not reset this time.

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
come on bot, #build !

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
go go gadget #build

**Pull request merged**
