### PR TITLE
Global keycache instead of 1 per thread.

### PR DESCRIPTION
**Pull request by yschaeff**

### CODE REVIEW

**Comment by yschaeff** [comment]
build

**Comment by yschaeff** [comment]
I said you #build bot!

**Comment by yschaeff** [comment]
@halderen @hodarh Review and merge please.

**Comment by halderen** [comment]
@yschaeff 
Reviewed, fine, though I dislike the lock being outside of the keycache, but it is contained within libhsm.
Want to merge but conflict in NEWS file.

**Pull request merged**
