### PR TITLE
OPENDNSSEC-726 disconnected KSK

### PR DESCRIPTION
**Pull request by halderen**

### CODE REVIEW

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build

**Comment by halderen** [comment]
#build 
I believe the previous build failure was just yet-another build system problem.  retry.

**Comment by yschaeff** [comment]
Reviewed. No comments.

**Pull request merged**
