### PR TITLE
OpenDNSSEC-99: add --force flag to ods-enforcer-db-setup

### PR DESCRIPTION
**Pull request by yschaeff**
and ods-hsmutil purge

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
All checks successful. Ready for the M4 merge.

**Comment by yschaeff** [comment]
missed this one

**Comment by halderen** [comment]
Conflicts needs resolving.

**Comment by yschaeff** [comment]
Ready for merge

**Pull request merged**
