### PR TITLE
OPENDNSSEC-853 serial_xfr_acquired not updated in state file

### PR DESCRIPTION
**Pull request by yschaeff**
Backport

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
@halderen @hodarh Review&merge at will.

**Comment by halderen** [comment]
Looked at this three times.  I cannot judge this change on face-value.  Also I'm worried that with future changes this may break again.  Would it be possible to create a unit test for it?

**Comment by yschaeff** [comment]
I have tried to create a test for it but it proved to be difficult. It needs shifting time in the signer without restarting the signer. I failed to do so. (btw you also merged PR576, this is a cherry pick from that)

**Pull request merged**
