### PR TITLE
OPENDNSSEC-465: ods-kaspcheck should trap algorithm mismatch

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
Please review and merge

**Comment by halderen** [comment]
This indeed checks whether for every KSK there is at least one ZSK with the same algorithm.  But should we not also check whether there aren't any ZSK without a counterpart KSK algorithm?  This is more of a notice of a dangling ZSK.  Just having a matching ZSK for every KSK is indeed sufficient.

**Pull request merged**
