### PR TITLE
Minimize was accessed as a flag but in reality it is a field of flags.

### PR DESCRIPTION
**Pull request by yschaeff**
I expect this change to trip up the mongrel test. If it does we need to update the test. If it doesn't we need another test.

### CODE REVIEW

**Comment by yschaeff** [comment]
What shall we do with the drunken #build bot?
What shall we do with the drunken build bot?
What shall we do with the drunken build bot?
Early in the morning?

**Comment by halderen** [comment]
Either case would warrant an issue in Jira.
For a comment in Jira: current database should not be changed, but flags should not be stored in a database in an integer, but as separate fields.

**Comment by yschaeff** [comment]
Ah nope. After inspecting further there appears to be no error. There appears to be a bit of redundancy in the database though but nothing we should act upon now. I'll let the buildbot finish the test before I kill of the PR.

**Comment by halderen** [comment]
Ok, that's a third case.

**Pull request closed without merging**
