### PR TITLE
adding time leap to enforcer.zones.delete_with_keys test case

### PR DESCRIPTION
**Pull request by hodarh**

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by halderen** [comment]
Hoda, pull requests 170 builds upon this code and now has a working test suite, so this one can be removed.

**Pull request merged**
