### PR TITLE
add sleep to make sure signer picks up new signconf

### PR DESCRIPTION
**Pull request by yschaeff**

### CODE REVIEW

**Comment by yschaeff** [comment]
#build

**Comment by yschaeff** [comment]
I don't think it is a enforcer problem. But rather a slow signer. Therefore I added a sleep instead of an ods_enforcer_idle. Lets see what happens.

**Comment by yschaeff** [comment]
#build
Ubuntu machine is complaining about missing files. :(

**Comment by yschaeff** [comment]
Looks good so far. I'm satisfied.

**Comment by halderen** [comment]
Sleep 3 it pretty low, but we'll try this for now.  The error in the tests "unable to apply parameter" is since the forcefully kill of ods- processes, and just is one more signal to not test using shell scripts.

**Pull request merged**
