### PR TITLE
clean up messy help (put the explanations of the command in its help …

### PR DESCRIPTION
**Pull request by hodarh**
…not usage)

### CODE REVIEW

**Comment by hodarh** [comment]
#build

**Comment by hodarh** [comment]
#build

**Comment by yschaeff** [comment]
Do we want this? I like you added better help. But why dumb down the usage information?

**Comment by hodarh** [comment]
When you run 'ods-enforcer help'  it shows all commands (usage part). It's a big messy list. I put their explanation into their help. Now I think we can find needed command more easily.

**Comment by hodarh** [comment]
ready to merge

**Pull request merged**
